### ISSUE TITLE
problem with tailwind postcss and/or jit?

### ISSUE THREAD

**Issue by froeb** [milesmcc/a17t#17]
When i use a main.css with
@import 'a17t/dist/tailwind.css';
@import 'a17t';

And a package.json with:
  "scripts": {
    "build": "cross-env NODE_ENV=production eleventy && set debug= && cross-env NODE_ENV=production postcss src/static/css/main.css --o _site/static/css/style.css",
[...]
},
  "devDependencies": {
    "@11ty/eleventy": "^0.11.0",
    "@11ty/eleventy-plugin-syntaxhighlight": "^3.0.1",
    "@neojp/tailwindcss-important-variant": "^1.0.1",
    "@tailwindcss/typography": "^0.3.1",
[...]
    "tailwindcss": "^2.0.2"
  },
  "dependencies": {
    "@tailwindcss/jit": "^0.1.18",
    "a17t": "^0.5.1",
    "autoprefixer": "^10.1.0",
    "cssnano": "^5.0.2",
    "postcss": "^8.2.1",
    "postcss-easy-import": "^3.0.0",
    "postcss-import": "^14.0.2",
    "postcss-preset-env": "^6.7.0",
    "tailwindcss-debug-screens": "^2.0.0"
  }
}

I get this error from issuing yarn build (the problem is in the last part of the output)

C:\laragon\Projects\tailwinds\neat\kai.froeb.net>yarn build
yarn run v1.22.5
warning ..\..\package.json: No license field
$ cross-env NODE_ENV=production eleventy && set debug= && cross-env NODE_ENV=production postcss src/static/css/main.css --o _site/static/css/style.css
(node:11800) [DEP0128] DeprecationWarning: Invalid 'main' field in 'C:\laragon\Projects\tailwinds\neat\kai.froeb.net\node_modules\emitter-mixin\package.json' of 'y'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
Writing _site/ds.htm from ./src/ds.html.
Writing _site/impressum.htm from ./src/impressum.html.
Writing _site/index.htm from ./src/index.html.
Writing _site/en/index.htm from ./src/en/index.html.
Writing _site/es/index.htm from ./src/es/index.html.
Writing _site/fr/index.htm from ./src/fr/index.html.
Writing _site/it/index.htm from ./src/it/index.html.
Writing _site/pt/index.htm from ./src/pt/index.html.
Copied 29 files / Wrote 8 files in 0.57 seconds (v0.11.1)

warn - You have enabled the JIT engine which is currently in preview.
warn - Preview features are not covered by semver, may introduce breaking changes, and can change at any time.

Source path: C:\laragon\Projects\tailwinds\neat\kai.froeb.net\src\static\css\main.css
Setting up new context...
JIT TOTAL: 3.063s

ParserError: Syntax Error at line: 1, column 26
    at C:\laragon\Projects\tailwinds\neat\kai.froeb.net\node_modules\a17t\dist\tailwind.css:1:10918
    at Parser.error (C:\laragon\Projects\tailwinds\neat\kai.froeb.net\node_modules\postcss-values-parser\lib\parser.js:127:11)
    at Parser.operator (C:\laragon\Projects\tailwinds\neat\kai.froeb.net\node_modules\postcss-values-parser\lib\parser.js:162:20)
    at Parser.parseTokens (C:\laragon\Projects\tailwinds\neat\kai.froeb.net\node_modules\postcss-values-parser\lib\parser.js:245:14)
    at Parser.loop (C:\laragon\Projects\tailwinds\neat\kai.froeb.net\node_modules\postcss-values-parser\lib\parser.js:132:12)
    at Parser.parse (C:\laragon\Projects\tailwinds\neat\kai.froeb.net\node_modules\postcss-values-parser\lib\parser.js:51:17)
    at parse (C:\laragon\Projects\tailwinds\neat\kai.froeb.net\node_modules\postcss-custom-properties\index.cjs.js:47:30)
    at C:\laragon\Projects\tailwinds\neat\kai.froeb.net\node_modules\postcss-custom-properties\index.cjs.js:333:24
    at C:\laragon\Projects\tailwinds\neat\kai.froeb.net\node_modules\postcss\lib\container.js:91:18
    at C:\laragon\Projects\tailwinds\neat\kai.froeb.net\node_modules\postcss\lib\container.js:74:18
    at Rule.each (C:\laragon\Projects\tailwinds\neat\kai.froeb.net\node_modules\postcss\lib\container.js:60:16) {
  postcssNode: Declaration {
    raws: { before: '', between: ':' },
    type: 'decl',
    parent: Rule {
      raws: [Object],
      type: 'rule',
      nodes: [Array],
      parent: [Root],
      source: [Object],
      selector: '.-space-y-0>:not([hidden])~:not([hidden])',
      lastEach: 12,
      indexes: [Object],
      [Symbol(isClean)]: false
    },
    source: { start: [Object], input: [Input], end: [Object] },
    prop: 'margin-top',
    value: 'calc(var(--spacing-0, 0)*-1*(1 - var(--tw-space-y-reverse)))',
    [Symbol(isClean)]: false
  }
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by froeb** [comment]
It seems, one needs to adapt one's postcss,config.js by adding:
module.exports = {
	plugins: {
		'postcss-import': {},
		'postcss-each': {},
		tailwindcss': {},
		'postcss-preset-env': {stage:4},
		'postcss-nested': {},
		'cssnano': {autoprefixer: false},
	}
}
and including them in package.json as well:
  "dependencies": {
    [...]
    "postcss": "^8.2.1",
    "postcss-each": "^0.10.0",
    "postcss-import": "^14.0.2",
    "postcss-nested": "^5.0.3",
    "postcss-preset-env": "^6.7.0",
    "postcss": "^8.2.2"
  }

in this case, my build task works without error message, however it does not end but "hangs". I can work around it by pressing strl-c, at the end,but that is kind of ugly. I had not to do this without a17t, there is no --watch or similar in the comand (see bove)

**Comment by milesmcc** [comment]
Very odd; not sure what we're doing that's breaking the process here... feel free to reopen if you're still running into this issue.
