### ISSUE TITLE
Docs: relative links broken on published version

### ISSUE THREAD

**Issue by tennox** [milesmcc/a17t#20]
In markdown files (e.g. [icon.md](https://github.com/milesmcc/a17t/blob/master/docs/information/icon.md)) the link `[shield](./shield)` points to the file in the same directory.

But in the published version, the link `<a href="./shield">shield</a>` points to the subpath `icon/shield`:
`https://a17t.miles.land/information/icon/shield` - which doesn't exist.

I guess it's a configuration option in whatever tool you're using for the published docs.
Good luck figuring that out :yum: 

Thanks for the great tool!

**Comment by milesmcc** [comment]
Thanks so much for the bug report! I've just fixed that relative link and rebuilt the docs, so the issue should be gone now.
